import { Space_Grotesk } from 'next/font/google';
import { Metadata } from "next";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '700'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`bg-[#0A0A0C] antialiased ${spaceGrotesk.className}`}
      >
        {children}
      </body>
    </html>
  );
}
